-- 1.0 init tables
CREATE TABLE public.aggregation_result
(
    id                                   BIGSERIAL PRIMARY KEY,
    account_code                         VARCHAR(255),
    account_number                       VARCHAR(255),
    accrued_interest_amount              NUMERIC(38, 2),
    accrued_interest_fix_amount          NUMERIC(38, 2),
    accrued_interest_fix_rubles_amount   NUMERIC(38, 2),
    accrued_interest_float_amount        NUMERIC(38, 2),
    accrued_interest_float_rubles_amount NUMERIC(38, 2),
    accrued_interest_rubles_amount       NUMERIC(38, 2),
    addition_flag                        VARCHAR(255),
    agreement_rank                       VARCHAR(255),
    average_principal_amount             NUMERIC(38, 2),
    average_principal_rubles_amount      NUMERIC(38, 2),
    avg_interest_rate                    NUMERIC(38, 2),
    balance_number                       VARCHAR(255),
    behavior_model_code                  VARCHAR(255),
    call_deposit_flag                    VARCHAR(255),
    client_id                            VARCHAR(255),
    comment1                             VARCHAR(255),
    comment2                             VARCHAR(255),
    commission_amount                    NUMERIC(38, 2),
    commission_rubles_amount             NUMERIC(38, 2),
    credential_type_number               VARCHAR(255),
    currency_id                          VARCHAR(255),
    current_principal_amount             NUMERIC(38, 2),
    current_principal_rub_amount         NUMERIC(38, 2),
    customer_rank                        VARCHAR(255),
    day_convention_code                  VARCHAR(255),
    deal_accrued_interest_amount         NUMERIC(38, 2),
    deal_currency_id                     VARCHAR(255),
    deal_current_principal_amount        NUMERIC(38, 2),
    deal_date                            TIMESTAMP(6),
    deal_id                              VARCHAR(255),
    deal_principal_payment_amount        NUMERIC(38, 2),
    deal_start_principal_amount          NUMERIC(38, 2),
    deposit_type_code                    VARCHAR(255),
    deposit_type_number                  VARCHAR(255),
    discriminator                        VARCHAR(255),
    end_date                             TIMESTAMP(6),
    evr_amortization_type                VARCHAR(255),
    evr_product                          VARCHAR(255),
    ftp_income_amount                    NUMERIC(38, 2),
    ftp_income_rubles_amount             NUMERIC(38, 2),
    has_no_schedule_flag                 VARCHAR(255),
    in_balance_amount                    NUMERIC(38, 2),
    in_balance_rubles_amount             NUMERIC(38, 2),
    interest_income_amount               NUMERIC(38, 2),
    interest_income_fix_amount           NUMERIC(38, 2),
    interest_income_fix_rubles_amount    NUMERIC(38, 2),
    interest_income_float_amount         NUMERIC(38, 2),
    interest_income_float_rubles_amount  NUMERIC(38, 2),
    interest_income_rubles_amount        NUMERIC(38, 2),
    interest_payment_amount              NUMERIC(38, 2),
    interest_payment_fix_amount          NUMERIC(38, 2),
    interest_payment_fix_rubles_amount   NUMERIC(38, 2),
    interest_payment_float_amount        NUMERIC(38, 2),
    interest_payment_float_rubles_amount NUMERIC(38, 2),
    interest_payment_rubles_amount       NUMERIC(38, 2),
    interest_payment_rule_day_number     BIGINT,
    interest_payment_rule_period_code    VARCHAR(255),
    interest_payment_rule_start_date     TIMESTAMP(6),
    interest_rate                        NUMERIC(38, 2),
    interest_rate_fixed                  NUMERIC(38, 2),
    interest_rate_float                  NUMERIC(38, 2),
    intergroup_flg                       VARCHAR(255),
    level1product_bank_number            VARCHAR(255),
    level2product_bank_number            VARCHAR(255),
    load_date                            TIMESTAMP(6),
    maturity_date                        TIMESTAMP(6),
    online_flag                          VARCHAR(255),
    out_balance_amount                   NUMERIC(38, 2),
    out_balance_rubles_amount            NUMERIC(38, 2),
    partition_report_date                VARCHAR(255),
    port_risks_scheduled_link_id         VARCHAR(255),
    prepayment_amount                    NUMERIC(38, 2),
    prepayment_rubles_amount             NUMERIC(38, 2),
    principal_payment_amount             NUMERIC(38, 2),
    principal_payment_rubles_amount      NUMERIC(38, 2),
    product_level1                       VARCHAR(255),
    product_level2                       VARCHAR(255),
    product_level3                       VARCHAR(255),
    product_level4                       VARCHAR(255),
    product_level5                       VARCHAR(255),
    product_rules_maturity               VARCHAR(255),
    program_number                       VARCHAR(255),
    rate_type_code                       VARCHAR(255),
    regular_payment_rule_day_number      BIGINT,
    regular_payment_rule_period_code     VARCHAR(255),
    regular_payment_rule_start_date      TIMESTAMP(6),
    report_date                          TIMESTAMP(6),
    segment                              VARCHAR(255),
    service_model_code                   VARCHAR(255),
    solve_id                             VARCHAR(255),
    source_code                          VARCHAR(255),
    start_date                           TIMESTAMP(6),
    start_principal_amount               NUMERIC(38, 2),
    start_principal_rubles_amount        NUMERIC(38, 2),
    term_group                           VARCHAR(255),
    time_bucket_code                     VARCHAR(255),
    time_bucket_number                   BIGINT,
    transfer_rate                        NUMERIC(38, 2),
    value_date                           TIMESTAMP(6),
    ytm_flag                             BIGINT
);

CREATE TABLE staged.aggregation_result
(
    LIKE public.aggregation_result INCLUDING ALL
);