spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/holder
    username: program
    password: test
    driver-class-name: org.postgresql.Driver

logging.level:
  org.springframework.batch: debug