ports:
  external: 32432

users:
  - name: program
    password: test

databases:
  - name: holder
    user: program
    schemas:
      - public
      - staged

config: |-
  max_connections = 20
  shared_buffers = 1GB
  effective_cache_size = 3GB
  maintenance_work_mem = 256MB
  checkpoint_completion_target = 0.9
  wal_buffers = 16MB
  default_statistics_target = 100
  random_page_cost = 1.1
  effective_io_concurrency = 200
  work_mem = 26214kB
  min_wal_size = 1GB
  max_wal_size = 4GB

resources:
  requests:
    cpu: 2
    memory: 4096Mi
  limits:
    cpu: 2
    memory: 4096Mi