ingress:
  enabled: true
  name: grafana
  domain: ru

prometheusService: prometheus

dashboards:
  - spring-boot
  - k8s-global
  - k8s-namespaces
  - k8s-pods

resources:
  requests:
    cpu: 500m
    memory: 2024Mi
  limits:
    cpu: 500m
    memory: 2024Mi