name: Build project
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "gradle"

      - name: Build project
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: clean build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"
